---
    language: node_js
    node_js:
      - "10"

    before_install:
      - set -e
      - if [ "${TRAVIS_TAG?}" ]; then
          AWS_BUCKET="pidservices.org";
          cp .env.production .env;
          AUTO_DEPLOY=true;
        elif [ "$TRAVIS_BRANCH" == "master" ]; then
          AWS_BUCKET="stage.pidservices.org";
          CLOUDFRONT_DISTRIBUTION_ID=$CLOUDFRONT_DISTRIBUTION_ID_STAGE;
          cp .env.stage .env;
          AUTO_DEPLOY=true;
        else
          AUTO_DEPLOY=false;
          AWS_BUCKET="stage.pidservices.org";
        fi
      - npm config set spin false

    install:
      - npm install
      - sudo pip install awscli
      - curl -sL https://sentry.io/get-cli/ | bash
      - sentry-cli --version

    script:
      - npm build
      - npm test

    after_success:
      # Send release information to Sentry
      - if [ "$AUTO_DEPLOY" == "true" ]; then
          GIT_TAG=$(git describe --tags --always $(git rev-list --tags --max-count=1));
          sentry-cli releases new beagle:${GIT_TAG} --finalize --project beagle;

          if [ "${TRAVIS_TAG?}" ]; then
            sentry-cli releases deploys beagle:${GIT_TAG} new -e production;
          else
            sentry-cli releases deploys beagle:${GIT_TAG} new -e stage;
          fi

          sentry-cli releases set-commits --auto beagle:${GIT_TAG};
        fi

    deploy:
      provider: s3
      access_key_id: $AWS_ACCESS_KEY
      secret_access_key: $AWS_SECRET_KEY
      bucket: $AWS_BUCKET
      region: eu-west-1
      skip_cleanup: true
      local_dir: build
      acl: public_read
      cache_control: "no-cache"
      on:
        all_branches: true

    after_deploy:
      - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY
      - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY
      # Allow `awscli` to make requests to CloudFront.
      - aws configure set preview.cloudfront true
      # Invalidate every object in the targeted distribution.
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"

    notifications:
      slack: datacite:Wt8En0ALoTA6Kjc5EOKNDWxN
      email: false
